name: Good Morning Workflow

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  good-morning:
    runs on: ubuntu-latest

    steps:
      - name: Greet
        run: echo "Good Morning!"
      
      - name: Print Date and Time
        run: date

      - name: Complete
        run: echo "Job Complete!"